# Generated by Django 4.0.6 on 2022-07-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheet',
            options={'ordering': ['id']},
        ),
    ]
